version: '3'
services:
  io-przepisy:
    build: .
    ports:
      - "80:8000"
    environment:
      - SECRET_KEY='SECRET'
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=io-przepisy
      - SUPER_EMAIL=admin@io-przepisy.com
      - SUPER_USERNAME=admin
      - SUPER_PASSWORD=mypass1234
  postgres:
    image: "postgres:11"
    environment:
      POSTGRES_PASSWORD: 'io-przepisy'
      POSTGRES_DB: 'CookBook'
    ports:
      - "5433:5432"
