# Generated by Django 2.2 on 2019-05-30 17:35

import autoslug.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=250, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'Składnik',
                'verbose_name_plural': 'Składniki',
            },
        ),
        migrations.CreateModel(
            name='IngredientsInRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, max_length=200, null=True, verbose_name='Ilość')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search4recipes.Ingredient', verbose_name='Składnik')),
            ],
            options={
                'verbose_name': 'Składnik w przepisie',
                'verbose_name_plural': 'Składniki w przepisach',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=250, unique=True, verbose_name='Jednostka miary')),
                ('measurement_use', models.CharField(max_length=60, verbose_name='Użycie jednostki')),
            ],
            options={
                'verbose_name': 'Miara',
                'verbose_name_plural': 'Miary',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=250, verbose_name='Nazwa przepisu')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nazwa_przepisu', unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/photos/', location='C:\\Users\\pawli\\Desktop\\io-przepisy\\IO-przepisy\\io_site\\media\\photos/'), upload_to='photos/', verbose_name='Zdjęcie przepisu')),
                ('mark', models.FloatField(default=0, verbose_name='Ocena')),
                ('text', models.TextField(default='', verbose_name='Treść przepisu')),
                ('amount_of_marks', models.IntegerField(default=0, verbose_name='Ilosc_ocen')),
                ('ingredients', models.ManyToManyField(through='search4recipes.IngredientsInRecipes', to='search4recipes.Ingredient')),
            ],
            options={
                'verbose_name': 'Przepis',
                'verbose_name_plural': 'Przepisy',
            },
        ),
        migrations.AddField(
            model_name='ingredientsinrecipes',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search4recipes.Measurement', verbose_name='Miara'),
        ),
        migrations.AddField(
            model_name='ingredientsinrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search4recipes.Recipe', verbose_name='Przepis'),
        ),
    ]
