# Generated by Django 2.2 on 2019-06-02 12:17

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search4recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipes',
            name='amount',
            field=models.FloatField(default=1, max_length=200, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='recipe_title', unique=True, verbose_name='slug'),
        ),
    ]
