# Generated by Django 2.2 on 2019-06-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search4recipes', '0002_auto_20190602_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='amount_of_marks',
            new_name='amount_of_rates',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='mark',
            new_name='rate',
        ),
    ]
