# Generated by Django 2.2 on 2019-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search4recipes', '0003_auto_20190602_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_use',
            field=models.CharField(max_length=60, verbose_name='Jednostka w przepisie'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\pawli\\Desktop\\io-przepisy\\IO-przepisy\\io_site\\media', verbose_name='Zdjęcie przepisu'),
        ),
    ]
