# Generated by Django 2.2 on 2019-06-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search4recipes', '0004_auto_20190604_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='Zdjęcie przepisu'),
        ),
    ]
