# Generated by Django 2.2 on 2019-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search4recipes', '0005_auto_20190604_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='', help_text='Użyj <br> aby przejść do nowje linii.', verbose_name='Treść przepisu'),
        ),
    ]
