# Generated by Django 2.2 on 2019-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search4recipes', '0006_auto_20190604_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty_level',
            field=models.IntegerField(choices=[(0, 'Łatwy'), (1, 'Średni'), (2, 'Trudny')], default=1, verbose_name='Poziom trudności'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(default=10, help_text='Czas przygotowania w minutach', verbose_name='Czas przygotowania'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='amount_of_rates',
            field=models.IntegerField(default=0, verbose_name='Ilość ocen'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nazwa przepisu'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='', help_text='Użyj &lt;br&gt; aby przejść do nowje linii.', verbose_name='Treść przepisu'),
        ),
    ]
